// 블로그 포스트 메타데이터 (sitemap·SEO·리스트에서 공유)
export const POSTS_META = [
  {
    slug: "landlord-income-tax-2025",
    title: "2025년 임대소득 종합소득세 신고 완벽 가이드",
    desc: "주택 임대소득 2000만원 이하·초과 구분, 분리과세 vs 종합과세 선택 기준, 필요경비 공제 항목까지 임대인이 꼭 알아야 할 세금 신고 총정리.",
    tag: "세금",
    tagColor: "#0fa573",
    date: "2025.03",
    datePublished: "2025-03-15",
    readTime: "8분",
    keywords: ["임대소득세", "종합소득세", "분리과세", "종합과세", "필요경비", "임대인 세금"],
  },
  {
    slug: "lease-renewal-right-guide",
    title: "계약갱신청구권 완벽 이해 — 임대인이 거절할 수 있는 경우",
    desc: "세입자가 계약갱신을 요구할 때 임대인이 정당하게 거절할 수 있는 6가지 사유, 실거주 요건, 위반 시 손해배상까지 실무 중심으로 정리.",
    tag: "임대차 3법",
    tagColor: "#5b4fcf",
    date: "2025.03",
    datePublished: "2025-03-20",
    readTime: "6분",
    keywords: ["계약갱신청구권", "임대차 3법", "갱신거절", "실거주 요건", "손해배상"],
  },
  {
    slug: "delinquent-tenant-guide",
    title: "월세 미납 세입자 대응 단계별 가이드 — 내용증명부터 명도까지",
    desc: "월세 1회 미납 시 대응법, 내용증명 발송 타이밍, 계약 해지 요건, 명도소송 절차까지. 임대인이 법적으로 손해 없이 처리하는 방법.",
    tag: "법률",
    tagColor: "#e8445a",
    date: "2025.03",
    datePublished: "2025-03-22",
    readTime: "10분",
    keywords: ["월세 미납", "내용증명", "명도소송", "계약 해지", "미납 대응"],
  },
  {
    slug: "commercial-lease-management",
    title: "상가 임대 관리 핵심 체크리스트 — 주거와 다른 점 총정리",
    desc: "상가 임대차보호법 적용 요건, 권리금 분쟁 예방법, 관리비 구성 기준, 부가세 처리까지. 상가 임대인이 반드시 알아야 할 실무 지식.",
    tag: "상가 임대",
    tagColor: "#e8960a",
    date: "2025.03",
    datePublished: "2025-03-25",
    readTime: "7분",
    keywords: ["상가 임대", "상가임대차보호법", "권리금", "부가세", "상가 관리비"],
  },
  {
    slug: "rental-yield-calculation",
    title: "임대 수익률 제대로 계산하는 법 — 표면 수익률 vs 실질 수익률",
    desc: "취득세·종합부동산세·소득세·건강보험료까지 반영한 실질 수익률 계산법. 임대 투자 전 반드시 확인해야 할 숫자들.",
    tag: "투자",
    tagColor: "#1a2744",
    date: "2025.03",
    datePublished: "2025-03-28",
    readTime: "9분",
    keywords: ["임대 수익률", "표면 수익률", "실질 수익률", "임대 투자", "부동산 투자"],
  },
  {
    slug: "vacancy-management-tips",
    title: "공실 기간을 줄이는 임대인 실전 전략 5가지",
    desc: "직방·다방·네이버 부동산 동시 등록 방법, 적정 임대료 설정, 공실 손실 계산, 인테리어 투자 수익성 분석까지 공실 최소화 실전 노하우.",
    tag: "공실 관리",
    tagColor: "#0d9488",
    date: "2025.03",
    datePublished: "2025-03-30",
    readTime: "5분",
    keywords: ["공실 관리", "공실 감소", "적정 임대료", "직방", "다방"],
  },
  {
    slug: "long-term-commercial-vacancy",
    title: "상가 장기 공실 탈출 플레이북 — 6개월 이상 비어있다면",
    desc: "용도 변경·렌트프리·중개수수료 2배·팝업스토어 등 장기 공실을 해소하는 고급 전략. 매각 시뮬레이션과 세금 최적화까지 임대인이 반드시 알아야 할 선택지.",
    tag: "공실 관리",
    tagColor: "#7c1d1d",
    date: "2026.04",
    datePublished: "2026-04-05",
    readTime: "8분",
    keywords: ["장기 공실", "상가 공실", "렌트프리", "용도 변경", "팝업스토어"],
  },
];

export function getPostMeta(slug) {
  return POSTS_META.find(p => p.slug === slug);
}
